### PR TITLE
component(): minor text fixes in documentation

### PR DESCRIPTION
**Pull request by florisvdh**

### CODE REVIEW

**Comment by finnlindgren** [comment]
Thanks! Can you run `devtools::document()` as well so the .Rd file becomes synchronised?

**Comment by florisvdh** [comment]
Sorry, I did it the quick way (in github). Will do that. And meanwhile, I'll check the rendered results :wink:.

**Comment by florisvdh** [comment]
Added some updates. Please check whether 89418e4 is right, it is a guess.

**Comment by finnlindgren** [comment]
Looks good! If the automated checks approve, I'll merge it, thanks!

**Pull request merged**
