### PR TITLE
Update gg.SpatialPolygons

### PR DESCRIPTION
**Pull request by ASeatonSpatial**
Tested this on my machine and when `ggpolypath` is installed it plots the polygons recognising the hole.  I removed `ggpolypath` and behaviour reverted to `geom_polygon` behaviour.  

I also updated the DESCRIPTION to add myself as contributor as discussed on the slack. 

One thing I am not sure if it matters, yesterday I did git fetch then git rebase to update my fork with the latest commits.  This morning I did git fetch then git merge to catch the commits from this morning.  I am not sure if this matters but I thought I'd mention it.  I'd usually do merge but yesterday I had read something that suggested rebase was better for this kind of thing so thought I should do that, just forgot this morning.  It may not matter at all but I wanted to mention it in case it does.

### CODE REVIEW

**Comment by ASeatonSpatial** [comment]
I attempted to link to geom_polypath in the documentation but I think I ran into an issue with linking to a function in a suggests package.  Not sure but I think that might have been why check failed due to bad links.  I've just removed the attempt to link in documentation for now

**Review by finnlindgren — COMMENTED** [review]
I'd replace the "[...]" in the documentation with \`...\`, so that the typesetting still treats them as code-like things, and add a comment about why one might want to make it use `ggpolypath` (i.e. the holes issue). But I also see in the `geom_polygon` documentation that supposedly "From R 3.6 and onwards it is possible to draw polygons with holes by providing a subgroup aesthetic that differentiates the outer ring points from those describing holes in the polygon.", so the question is then how to construct that information (the example in the documentation isn't a general example, I think).

**Comment by finnlindgren** [comment]
I'll merge the PR, but it seems all we really need is to use
```
  dmap <- aes_string(x = "long", y = "lat", group = "id", subgroup = "hole")
```
to make it work with `ggplot2::geom_polygon`, which would remove the need to Suggest another package.

**Comment by finnlindgren** [comment]
"group" seems to be different between the main polygon and the hole in it, but "id" is the same.

**Comment by ASeatonSpatial** [comment]
Ah good find, I searched briefly but found only convoluted solutions in the first few results, or the suggestion to use ggpolypath. 

`dmap <- aes_string(x = "long", y = "lat", group = "id", subgroup = "hole") `

As you say, looking at the example in the documentation this seems like all that is required.  I would double check it works as expected when `hole` is a logical variable.  The example uses an integer.

**Comment by finnlindgren** [comment]
Yes, seems to work (I thing it is converted to a factor internally). I've updated it to use that method when ggpolypath isn't available, and may remove ggpolypath when fully confirmed to work. I've tested it with holes defined both in clockwise and counterclockwise order, but Polygons standardises it internally (but still has two variables, holes, and ringDir that _jointly_ determine it, which is a bit annoying; however, fortify only produces the hole variable)

**Pull request merged**
